# github的打包和部署的demo
name: GitHub Actions Build and Deploy Demo
# 整个流程在master分支发生push事件时触发。
on:
  push:
    branches:
      - master
jobs:
  # 只有一个job，运行在虚拟机环境ubuntu-latest。
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # name 表示这次步骤的名字
      - name: Checkout
        # 这个action表示检查你的仓库是不是在$GITHUB_WORKSPACE下面。这样整个工作流才能正常的访问。
        uses: actions/checkout@V3
        with:
          persist-credentials: false
      - name: Install and Build
        run: |
          npm install
          npm run-script build
      - name: Deploy
        # 这个action是用于部署页面到github上。
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
